name: Deploy Lambda

on:
  push:
    branches: [ "main" ]

env:
  FILENAME: dividend_announcements.zip

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Build Zip file
        run: bash ./create_package.sh
      - name: Push ZipFile Up
        run: aws s3 cp --region ${{ vars.AWS_REGION }} ./${{ env.FILENAME }} s3://function-bucket-drm
      - name: Update Lambda
        run: aws lambda update-function-code --function-name app-dividends --s3-bucket function-bucket-drm --s3-key ${{ env.FILENAME }}
      - name: Zip file Cleanup
        run: aws s3 rm --region ${{ vars.AWS_REGION }} s3://function-bucket-drm/${{ env.FILENAME }}
